import { createPinia } from 'pinia';
import { createApp } from 'vue';
import router from '@/router/index';
import '@/assets/scss/_global.scss';
import '@/assets/scss/_reset.scss';
import App from './App.vue';
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
